export const INCREMENT_ADULT = 'INCREMENT_ADULT';
export const DECREMENT_ADULT = 'DECREMENT_ADULT';

export const INCREMENT_CHILDREN = 'INCREMENT_CHILDREN';
export const DECREMENT_CHILDREN = 'DECREMENT_CHILDREN';

