export const INCREMENT_ADULT = 'INCREMENT_ADULT';
export const DECREMENT_ADULT = 'DECREMENT_ADULT';

export const INCREMENT_SENIOR = 'INCREMENT_SENIOR';
export const DECREMENT_SENIOR = 'DECREMENT_SENIOR';

export const INCREMENT_CHILDREN = 'INCREMENT_CHILDREN';
export const DECREMENT_CHILDREN = 'DECREMENT_CHILDREN';

export const INCREMENT_INFANT = 'INCREMENT_INFANT';
export const DECREMENT_INFANT = 'DECREMENT_INFANT';
